### ISSUE TITLE
Redgifs doesn't work

### ISSUE THREAD

**Issue by Anceph** [ubershmekel/redditp#138]
Redgifs links doesn't work.

**Comment by ubershmekel** [comment]
Gosh, again...

**Comment by ubershmekel** [comment]
I'm pushing out a fix that will create an iframe for redgifs. The sad part is that "auto-next" doesn't work. You can either set the auto-next to a higher time duration, or just disable it and manually next.

The problem is that redgifs disabled access to their APIs. So either we need a server to circumvent the problem, or to find some other solution. I wonder why they have such nice api docs if they don't want folks to use them https://api.redgifs.com/docs/

**Comment by Hrxn** [comment]
@ubershmekel Do you know when redgifs disabled access to their APIs perchance?

**Comment by maitikeisi** [comment]
https://twitter.com/RedGifsOfficial/status/1517232596459139072

seems to be wider problem at RedGIFs end. Hopefully the API starts working again too when they get everything solved.

**Comment by ubershmekel** [comment]
This was a deliberate change on their end to block CORS requests. I doubt that it's some sort of outage.

**Comment by ubershmekel** [comment]
I saw redditpx used a proxy to fix this issue. I don't have plans on making a proxy, so the iframes will have  to do for now. Closing the issue unless folks have a better idea.
