### ISSUE TITLE
redditp doesnt work when i put in a subreddit however it works when i put in a user

### ISSUE THREAD

**Issue by kwasiasem** [ubershmekel/redditp#159]
![image](https://github.com/ubershmekel/redditp/assets/141968735/93e3f5d7-361c-4309-8291-8c5c4c5fae38)
![image](https://github.com/ubershmekel/redditp/assets/141968735/ada0f020-6608-4824-b781-9f6eb8307f3c)

 as you can see im on chrome and i have a windows 10 computer with the latest update. this is the same on my iphone 12. i have just changed wifi today which may be why? other than that i am not sure and am also unsure if others are experiencing this issue. please try to resolve this

**Comment by ubershmekel** [comment]
https://redditp.com/r/aww/ works for me in a regular window and an incognito window.

Can you try on another machine?

Can you try to disable all extensions?

**Comment by SoulSilver08** [comment]
for some reason it doesn´t work without a slash (/) after the subreddit name in the url
![Wo_Slash](https://github.com/ubershmekel/redditp/assets/139677154/e74df9e6-0e24-4461-b158-439afe378c4c)
![W_Slash](https://github.com/ubershmekel/redditp/assets/139677154/0abda8a4-6f10-4357-be67-b090e2e35a15)

**Comment by kwasiasem** [comment]
> https://redditp.com/r/aww/ works for me in a regular window and an incognito window.
> 
> Can you try on another machine?
> 
> Can you try to disable all extensions?
seems all i had to do was just put / at the end of the url

**Comment by ubershmekel** [comment]
Seems that requesting the following:

https://www.reddit.com/r/aww.json?&jsonp=jQuery341017684215129869707_1691731760220&_=1691731760221

Causes a 301 redirect to:

https://www.reddit.com/r/aww.json/?&jsonp=jQuery341017684215129869707_1691731760220&_=1691731760221

I don't know if it's new that reddit does this redirect, or if the browser only recently started to fail on this. But I don't remember this ever being a problem.

Thank you for figuring it out.

Should be fixed in https://github.com/ubershmekel/redditp/commit/ee86dd1f49d5bcb719431565e179d677cb50a81c

Please retest and let me know.
