### ISSUE TITLE
Can't view multiple subreddits on mobile

### ISSUE THREAD

**Issue by jacobdale211** [ubershmekel/redditp#174]
Failed ajax, maybe a bad url? Sorry about that :(, please alert ubershmekel on GitHub

Same link works on desktop, just not mobile. Above is the error message received

**Comment by ubershmekel** [comment]
Thank you for this report. I also got this report: https://www.reddit.com/r/redditp/comments/1d68lnl/no_working_anymore/

It's broken for all of reddit unfortunately. See the bug report at:

https://www.reddit.com/r/redditdev/comments/1d5ru27/api_error_when_fetching_multireddit_data/

Fortunately it seems a reddit admin reported this too.

Maybe this is a sign that redditp should have a back end someday.

**Comment by efeuentertainment** [comment]
(⁠┛⁠ಸ⁠_⁠ಸ⁠)⁠┛⁠彡⁠┻⁠━⁠┻

> sir_axolotl_alot Reddit Admin :snoo: 0 points 6 days ago
> 
> So I've been doing a little digging, and it turns out that these URLs are not officially supported as part of our Developer API. These are internal URLs that our services use to communicate with each other. Which means is kind of lucky that they worked up until anyway. But being undocumented internal URLs, they can break without warning, unfortunately. And last week our product teams decided to make changes to our apps which affected these URLs.
> 
> We do have an officially supported endpoint for a single subreddit's hot sorting, so I would suggest sending a separate call for each subreddit, then merging the resulting listings. Hope this helps!
https://www.reddit.com/dev/api/#GET_hot

**Comment by ubershmekel** [comment]
Y'all aren't gonna believe how simple the fix was. Turns out that on old.reddit.com the API works just fine.

I got the idea when https://www.reddit.com/r/MadeMeSmile/comments/1e07552/imagine_busking_on_the_street_and_the_artist_of/ linked to https://old.reddit.com/r/MadeMeSmile/comments/1d8xfq5/busker_in_coffee_shop_singing_matisyahu_one_day/ and I had this moment of wondering if https://old.reddit.com/r/MadeMeSmile/comments/1d8xfq5/busker_in_coffee_shop_singing_matisyahu_one_day/.json worked and when it di I then checked https://old.reddit.com/r/MadeMeSmile+aww/.json with a mobile user agent and the rest was history.
